### ISSUE TITLE
Cannot login for CG account linked to Google account

### ISSUE THREAD

**Issue by dbdr** [s-vivien/CGBenchmark#1]
My CodinGame account is linked to my Google account (maybe not the best idea, but I don't know if/how it can be changed), so I don't have a password to enter in the configuration.

I worked around it by making CGBenchmark optionally get the account cookie and IDE, basically working as it did before https://github.com/s-vivien/CGBenchmark/commit/952df6222418eb3362c77e1b90b53987554c6b96

Is this the right approach? My code should still use the login/passwd if the cookie is not provided. I can send a PR if you want to review/merge it.

**Comment by s-vivien** [comment]
Hi,

I've heard about some people trying to get a login/pwd for their gmail-linked account. I believe that the "official" workaround is to select _I forgot my password_ and it will generate a brand new password, sent to your gmail inbox.

However, being able to use both login/pwd and cookie in CGBenchmark could be interesting.
In order to not mess the configuration file too much, I would recomand to keep the IDE retrieval as it is right now and just bypass the loginApi call if the cookie is provided.

Feel free to submit a PR for that if you want :)
